<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0.1 (Python 3.12.3 on win32)" generated="2024-08-02T09:43:55.270882" rpa="false" schemaversion="5">
<suite id="s1" name="10 04 Validations" source="c:\Users\a315707\OneDrive - Deutsche Telekom AG\Schulungen\Programmierung\Python\PythonLearning\10_Apply_Validations\10_04_Validations.robot">
<test id="s1-t1" name="TC_10_04_01 Validate Text" line="9">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2024-08-02T09:43:55.601442" level="INFO">Opening browser 'Firefox' to base url 'https://thetestingworld.com/testings'.</msg>
<msg time="2024-08-02T09:43:58.744776" level="WARN">Problem reading geckodriver versions: error sending request for url (https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/geckodriver/geckodriver-support.json). Using latest geckodriver version</msg>
<msg time="2024-08-02T09:43:58.745776" level="WARN">Exception managing firefox: error sending request for url (https://github.com/mozilla/geckodriver/releases/latest)</msg>
<msg time="2024-08-02T09:43:58.746772" level="WARN">Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)</msg>
<msg time="2024-08-02T09:44:00.855449" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<msg time="2024-08-02T09:44:00.855449" level="FAIL">WebDriverException: Message: Service C:\Program Files\Wpy64-31230\python-3.12.3.amd64\geckodriver.exe unexpectedly exited. Status code was: 1
</msg>
<arg>${var1}</arg>
<arg>Firefox</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2024-08-02T09:43:55.601442" elapsed="5.261112">WebDriverException: Message: Service C:\Program Files\Wpy64-31230\python-3.12.3.amd64\geckodriver.exe unexpectedly exited. Status code was: 1
</status>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:00.863594" elapsed="0.000000"/>
</kw>
<kw name="Element Text Should Be" owner="SeleniumLibrary">
<arg>xpath://div[@id='tab-content1']/p</arg>
<arg>Register now and kick start your career as a Software Testing Pro!</arg>
<doc>Verifies that element ``locator`` contains exact the text ``expected``.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:00.864600" elapsed="0.000000"/>
</kw>
<kw name="Element Should Contain" owner="SeleniumLibrary">
<arg>xpath://div[@id='tab-content1']/p</arg>
<arg>Software Testing</arg>
<doc>Verifies that element ``locator`` contains text ``expected``.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:00.864600" elapsed="0.001196"/>
</kw>
<kw name="Input Text" owner="SeleniumLibrary">
<arg>name:fld_username</arg>
<arg>Hello</arg>
<doc>Types the given ``text`` into the text field identified by ``locator``.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:00.865796" elapsed="0.000000"/>
</kw>
<kw name="Close Browser" owner="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:00.866833" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2024-08-02T09:43:55.600386" elapsed="5.266447">WebDriverException: Message: Service C:\Program Files\Wpy64-31230\python-3.12.3.amd64\geckodriver.exe unexpectedly exited. Status code was: 1
</status>
</test>
<test id="s1-t2" name="TC_10_04_01 Validate Text" line="43">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2024-08-02T09:44:00.869896" level="INFO">Opening browser 'Firefox' to base url 'https://thetestingworld.com/testings'.</msg>
<msg time="2024-08-02T09:44:01.528793" level="WARN">Problem reading geckodriver versions: error sending request for url (https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/geckodriver/geckodriver-support.json). Using latest geckodriver version</msg>
<msg time="2024-08-02T09:44:01.531009" level="WARN">Exception managing firefox: error sending request for url (https://github.com/mozilla/geckodriver/releases/latest)</msg>
<msg time="2024-08-02T09:44:03.565957" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<msg time="2024-08-02T09:44:03.566476" level="FAIL">WebDriverException: Message: Service C:\Program Files\Wpy64-31230\python-3.12.3.amd64\geckodriver.exe unexpectedly exited. Status code was: 1
</msg>
<arg>${var1}</arg>
<arg>Firefox</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2024-08-02T09:44:00.868890" elapsed="6.863696">WebDriverException: Message: Service C:\Program Files\Wpy64-31230\python-3.12.3.amd64\geckodriver.exe unexpectedly exited. Status code was: 1
</status>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:07.732586" elapsed="0.000000"/>
</kw>
<kw name="Element Text Should Be" owner="SeleniumLibrary">
<arg>xpath://div[@id='tab-content1']/p</arg>
<arg>Register now and kick start your career as a Software Testing Pro!</arg>
<doc>Verifies that element ``locator`` contains exact the text ``expected``.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:07.732586" elapsed="0.001499"/>
</kw>
<kw name="Element Should Contain" owner="SeleniumLibrary">
<arg>xpath://div[@id='tab-content1']/p</arg>
<arg>Software Testing</arg>
<doc>Verifies that element ``locator`` contains text ``expected``.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:07.734085" elapsed="0.000000"/>
</kw>
<kw name="Input Text" owner="SeleniumLibrary">
<arg>name:fld_username</arg>
<arg>Hello</arg>
<doc>Types the given ``text`` into the text field identified by ``locator``.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:07.735097" elapsed="0.000000"/>
</kw>
<kw name="Close Browser" owner="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="NOT RUN" start="2024-08-02T09:44:07.735097" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2024-08-02T09:44:00.868890" elapsed="6.866207">WebDriverException: Message: Service C:\Program Files\Wpy64-31230\python-3.12.3.amd64\geckodriver.exe unexpectedly exited. Status code was: 1
</status>
</test>
<status status="FAIL" start="2024-08-02T09:43:55.293339" elapsed="12.444188"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="10 04 Validations">10 04 Validations</stat>
</suite>
</statistics>
<errors>
<msg time="2024-08-02T09:43:58.744776" level="WARN">Problem reading geckodriver versions: error sending request for url (https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/geckodriver/geckodriver-support.json). Using latest geckodriver version</msg>
<msg time="2024-08-02T09:43:58.745776" level="WARN">Exception managing firefox: error sending request for url (https://github.com/mozilla/geckodriver/releases/latest)</msg>
<msg time="2024-08-02T09:43:58.746772" level="WARN">Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)</msg>
<msg time="2024-08-02T09:44:00.867844" level="WARN">Multiple tests with name 'TC_10_04_01 Validate Text' executed in suite '10 04 Validations'.</msg>
<msg time="2024-08-02T09:44:01.528793" level="WARN">Problem reading geckodriver versions: error sending request for url (https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/geckodriver/geckodriver-support.json). Using latest geckodriver version</msg>
<msg time="2024-08-02T09:44:01.531009" level="WARN">Exception managing firefox: error sending request for url (https://github.com/mozilla/geckodriver/releases/latest)</msg>
</errors>
</robot>
